# Generated by Django 4.2.2 on 2024-06-28 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_username_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_users', 'Может просматривать список пользователей сервиса.'), ('can_edit_is_active', 'Может блокировать пользователей сервиса.')], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
