# Generated by Django 4.2.2 on 2024-06-28 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_options_user_is_block'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_users', 'Может просматривать список пользователей сервиса.'), ('change_is_block', 'Может блокировать пользователей сервиса.')], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
