# Generated by Django 4.2.2 on 2024-06-25 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing_attempt',
            name='mailing_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing', verbose_name='id рассылки'),
            preserve_default=False,
        ),
    ]
