# Generated by Django 4.2.2 on 2024-06-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_mailing_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='frequency',
            field=models.CharField(choices=[('per_day', 'раз в день'), ('per_week', 'раз в неделю'), ('per_month', 'раз в месяц')], default='per_day', max_length=50, verbose_name='периодичность'),
        ),
        migrations.AlterField(
            model_name='mailing_attempt',
            name='mail_response',
            field=models.CharField(max_length=50, verbose_name='ответ почтового сервера'),
        ),
    ]
