# Generated by Django 4.2.2 on 2024-06-28 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_alter_mailing_frequency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='massage',
            options={'permissions': [('view_mailing', 'Может просматривать любые рассылки.'), ('view_users', 'Может просматривать список пользователей сервиса.'), ('can_edit_status', 'Может отключать рассылки.'), ('can_edit_is_active', 'Может блокировать пользователей сервиса.')], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
    ]
