# Generated by Django 4.2 on 2024-07-02 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_remove_mailing_attempt_is_active_mailing_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='mailing',
        ),
        migrations.RemoveField(
            model_name='mailing_attempt',
            name='mailing',
        ),
        migrations.RemoveField(
            model_name='massage',
            name='mailing',
        ),
        migrations.AddField(
            model_name='mailing',
            name='clients',
            field=models.ManyToManyField(related_name='mailing', to='mailing.customers', verbose_name='Клиенты для рассылки'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='massage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.massage', verbose_name='Cообщение'),
        ),
    ]
