# Generated by Django 4.2.2 on 2024-06-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_alter_massage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing_attempt',
            options={'permissions': [('can_edit_is_active', 'Может отключать рассылки.')], 'verbose_name': 'Попытка рассылки', 'verbose_name_plural': 'Попытки рассылок'},
        ),
        migrations.AlterModelOptions(
            name='massage',
            options={'permissions': [('view_mailing', 'Может просматривать любые рассылки.')], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AddField(
            model_name='mailing_attempt',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Статус Рассылки'),
        ),
    ]
