# Generated by Django 4.2 on 2024-07-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_remove_customers_mailing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing_attempt',
            name='mail_response',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ответ почтового сервера'),
        ),
    ]
