# Generated by Django 4.2 on 2024-07-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_alter_mailing_attempt_mail_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Конец рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='next_day',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Следующая отправка рассылки'),
        ),
    ]
