# Generated by Django 4.2.2 on 2024-06-28 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_customers_owner_massage_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing_attempt',
            options={'permissions': [('change_is_active', 'Может отключать рассылки.')], 'verbose_name': 'Попытка рассылки', 'verbose_name_plural': 'Попытки рассылок'},
        ),
    ]
