# Generated by Django 5.0.6 on 2024-06-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0008_alter_mailing_attempt_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='mailing_status',
            field=models.CharField(choices=[('created', 'создана'), ('executing', 'запущена'), ('finished', 'закончена успешно'), ('error', 'законечена с ошибками')], default='created', max_length=80, verbose_name='статус рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing_attempt',
            name='status',
            field=models.CharField(choices=[('successfully', 'успешно'), ('not_successful', 'не успешно')], default=None, verbose_name='статус попытки'),
        ),
    ]
